// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJtQy73F0_jkrg1vgwqtnqjavl-7a9ao',
    appId: '1:13870628872:web:c1a93e6e30d707f56391bd',
    messagingSenderId: '13870628872',
    projectId: 'cryptalert-13450',
    authDomain: 'cryptalert-13450.firebaseapp.com',
    storageBucket: 'cryptalert-13450.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-dwElVuGWHw9DC6nj8s3SPtXjSq8Fvs',
    appId: '1:13870628872:android:b9754ff98345a7466391bd',
    messagingSenderId: '13870628872',
    projectId: 'cryptalert-13450',
    storageBucket: 'cryptalert-13450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94q24mQlifKv7FMmwpWoMxgPhZgmiBnQ',
    appId: '1:13870628872:ios:5b915985bc8d440f6391bd',
    messagingSenderId: '13870628872',
    projectId: 'cryptalert-13450',
    storageBucket: 'cryptalert-13450.appspot.com',
    iosClientId: '13870628872-cs06rt7o9ubi0caen92qa7kmm9lkb8ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptAlert',
  );
}
